// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

type frontUserDao struct {
	*internal.FrontUserDao
}

var (
	FrontUser = frontUserDao{internal.NewFrontUserDao()}
)
