// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

type plcAlarmDao struct {
	*internal.PlcAlarmDao
}

var (
	PlcAlarm = plcAlarmDao{internal.NewPlcAlarmDao()}
)
