// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// shortLinkLogDao is the data access object for the table hg_short_link_log.
// You can define custom methods on it to extend its functionality as needed.
type shortLinkLogDao struct {
	*internal.ShortLinkLogDao
}

var (
	// ShortLinkLog is a globally accessible object for table hg_short_link_log operations.
	ShortLinkLog = shortLinkLogDao{internal.NewShortLinkLogDao()}
)

// Add your custom methods and functionality below.
