// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// shortLinkDao is the data access object for the table hg_short_link.
// You can define custom methods on it to extend its functionality as needed.
type shortLinkDao struct {
	*internal.ShortLinkDao
}

var (
	// ShortLink is a globally accessible object for table hg_short_link operations.
	ShortLink = shortLinkDao{internal.NewShortLinkDao()}
)

// Add your custom methods and functionality below.
